{{--
    The donation acknowledgement, as a PDF.

    Rendered by DomPDF from the RECEIPT ROW: everything here was frozen at
    issue. Inline styles and a table layout on purpose — DomPDF supports a
    subset of CSS, and a receipt is a page with a table on it.
--}}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $receipt->receipt_number }}</title>
    <style>
        @page { margin: 20mm 18mm; }
        body { font-family: DejaVu Sans, sans-serif; font-size: 11pt; color: #0F1A17; line-height: 1.45; }
        h1 { font-size: 18pt; margin: 0 0 4pt; color: #0B4D3F; }
        h2 { font-size: 12pt; margin: 18pt 0 6pt; color: #0B4D3F; }
        .muted { color: #5E706B; font-size: 9.5pt; }
        table { width: 100%; border-collapse: collapse; }
        td, th { padding: 5pt 6pt; vertical-align: top; text-align: left; }
        .grid td { border-bottom: 1px solid #E2E8E5; }
        .grid th { width: 38%; color: #5E706B; font-weight: normal; border-bottom: 1px solid #E2E8E5; }
        .amount { font-size: 16pt; font-weight: bold; }
        .box { border: 1px solid #E2E8E5; padding: 10pt 12pt; margin-top: 12pt; }
        .footer { margin-top: 24pt; font-size: 8.5pt; color: #5E706B; border-top: 1px solid #E2E8E5; padding-top: 8pt; }
        .logo { height: 46pt; }
    </style>
</head>
<body>
    <table>
        <tr>
            <td style="width: 60%; padding: 0;">
                @if ($logoPath)
                    <img class="logo" src="{{ $logoPath }}" alt="">
                @endif
                <h1>{{ $organisation['name'] }}</h1>
                <div class="muted">
                    @if ($organisation['registration'] && ! str_contains($organisation['registration'], '{{'))
                        {{ __('Registration no.') }} {{ $organisation['registration'] }}<br>
                    @endif
                    @if ($organisation['tin'])
                        TIN {{ $organisation['tin'] }}<br>
                    @endif
                    @if ($organisation['address'])
                        {{ $organisation['address'] }}<br>
                    @endif
                    {{ collect([$organisation['email'], $organisation['phone']])->filter(fn ($v) => $v && ! str_contains($v, '{{'))->implode(' · ') }}
                </div>
            </td>
            <td style="width: 40%; padding: 0; text-align: right;">
                <div class="muted">{{ __('Receipt') }}</div>
                <div style="font-size: 13pt; font-weight: bold;">{{ $receipt->receipt_number }}</div>
                <div class="muted">{{ __('Issued') }} {{ $receipt->issued_on->format('j F Y') }}</div>
            </td>
        </tr>
    </table>

    <h2>{{ __('Donation acknowledgement') }}</h2>

    <table class="grid">
        <tr><th>{{ __('Received from') }}</th><td>{{ $receipt->donor_name }}</td></tr>
        <tr><th>{{ __('Amount') }}</th><td class="amount">{{ $receipt->amount->format() }}</td></tr>
        <tr><th>{{ __('In words') }}</th><td>{{ $receipt->amount_in_words }}</td></tr>
        <tr><th>{{ __('Towards') }}</th><td>{{ $receipt->cause }}</td></tr>
        <tr><th>{{ __('Received on') }}</th><td>{{ $receipt->donated_on->format('j F Y') }}</td></tr>
        <tr><th>{{ __('Payment reference') }}</th><td>{{ $receipt->payment_reference }}</td></tr>
        @if ($receipt->deductible_amount->isPositive() && ! $receipt->deductible_amount->equals($receipt->amount))
            <tr><th>{{ __('Of which eligible for tax relief') }}</th><td>{{ $receipt->deductible_amount->format() }}</td></tr>
        @endif
    </table>

    <div class="box">
        @foreach ($paragraphs as $paragraph)
            <p style="margin: 0 0 6pt;">{{ $paragraph }}</p>
        @endforeach
        @if ($receipt->cites_approval && $receipt->approval_reference)
            <p class="muted" style="margin: 6pt 0 0;">{{ __('Approval reference') }}: {{ $receipt->approval_reference }}@if ($receipt->approval_validity) — {{ $receipt->approval_validity }}@endif</p>
        @endif
    </div>

    <div class="footer">
        {{ __('This document was generated by :name and can be verified by quoting the receipt number.', ['name' => $organisation['name']]) }}
        @if ($receipt->authentication)
            {{ __('Authentication') }}: {{ $receipt->authentication }}
        @endif
        <br>{{ $organisation['website'] }}
    </div>
</body>
</html>
