<?php

declare(strict_types=1);

namespace App\Support;

use PragmaRX\Google2FAQRCode\Google2FA;
use SensitiveParameter;
use Throwable;

/**
 * TOTP, for the public donor account.
 *
 * ── Why this exists when Filament already does TOTP ─────────────────────────
 *
 * Filament's implementation lives inside Filament's login flow and is reachable
 * only from the admin panel. Donors do not sign in there — deliberately, since
 * a public form that authenticated staff would be a bypass of the panel's
 * mandatory second factor.
 *
 * So the public side needs its own enrolment and its own challenge. It uses the
 * same library, the same columns and the same contracts on `User`, so an
 * account has one second factor rather than two that disagree.
 *
 * ── The secret does not touch the database until it is proved ───────────────
 *
 * Enrolment holds the candidate secret in the session and writes it only once a
 * code generated from it has been verified. `User::saveAppAuthenticationSecret()`
 * sets `two_factor_confirmed_at` at the same moment it stores the secret —
 * Filament's contract, and the right one — so a secret in the column means an
 * account with working two-factor. There is no half-enrolled state to reason
 * about, and no window in which the column says a factor exists that the person
 * cannot actually produce.
 */
class TwoFactor
{
    /** How many recovery codes to issue. */
    public const RECOVERY_CODE_COUNT = 8;

    public function __construct(private readonly Google2FA $google2fa) {}

    /** A fresh, unassigned secret. */
    public function generateSecret(): string
    {
        return $this->google2fa->generateSecretKey();
    }

    /**
     * Whether this code was generated by this secret, near enough to now.
     *
     * The library compares against a window of adjacent time steps rather than
     * only the current one, because a phone's clock and a server's clock are
     * never exactly the same and a strict comparison rejects perhaps a third of
     * legitimate codes near a step boundary. The window is small enough that a
     * guessed code is still one in a million; the rate limit on the challenge
     * is what stops somebody making a million guesses.
     */
    public function verify(#[SensitiveParameter] string $secret, #[SensitiveParameter] string $code): bool
    {
        $code = preg_replace('/\s+/', '', $code) ?? '';

        if (! preg_match('/^\d{6}$/', $code)) {
            return false;
        }

        try {
            return (bool) $this->google2fa->verifyKey($secret, $code);
        } catch (Throwable) {
            // A malformed secret — a column edited by hand, a half-restored
            // backup. Refuse rather than throw: a broken secret must fail the
            // challenge, not produce a 500 on the sign-in path.
            return false;
        }
    }

    /**
     * The code an authenticator app would be showing right now.
     *
     * Exists for tests and for the enrolment screen's own sanity — never shown
     * to a user, because a server that can display the current code is a server
     * that has made the second factor into a first one.
     */
    public function currentCode(#[SensitiveParameter] string $secret): string
    {
        return $this->google2fa->getCurrentOtp($secret);
    }

    /**
     * The QR code, as a data URI to inline in the page.
     *
     * Inlined rather than served from a route, and that is the security point
     * rather than a convenience: a URL that renders somebody's TOTP secret is a
     * URL that can be requested, logged by a proxy, and left in a browser
     * history. This never leaves the response it belongs to.
     *
     * Returns null when the server cannot draw one. That is not a failure —
     * every authenticator app accepts a typed key, and the enrolment screen
     * shows the key alongside the image for exactly this reason.
     */
    public function qrCodeDataUri(#[SensitiveParameter] string $secret, string $issuer, string $holder): ?string
    {
        try {
            $svg = $this->google2fa->getQRCodeInline($issuer, $holder, $secret);
        } catch (Throwable) {
            return null;
        }

        return 'data:image/svg+xml;base64,'.base64_encode($svg);
    }

    /**
     * The `otpauth://` URI, for typing or for a link on the same device.
     *
     * Shown as the manual key on the enrolment screen. Somebody setting this up
     * on the phone they are reading it on cannot scan their own screen.
     */
    public function provisioningUri(#[SensitiveParameter] string $secret, string $issuer, string $holder): string
    {
        return $this->google2fa->getQRCodeUrl($issuer, $holder, $secret);
    }

    /**
     * Single-use codes for the day the phone is lost.
     *
     * Without them, losing the device means losing the account — and the way
     * that gets resolved in practice is somebody at the foundation switching
     * two-factor off over the telephone for whoever asks, which is the whole
     * control gone.
     *
     * Grouped with a hyphen because these get written down, and a run of twenty
     * characters is copied wrongly.
     *
     * @return array<int, string>
     */
    public function generateRecoveryCodes(): array
    {
        return collect(range(1, self::RECOVERY_CODE_COUNT))
            ->map(fn (): string => str()->lower(str()->random(10)).'-'.str()->lower(str()->random(10)))
            ->all();
    }

    /**
     * Compare a submitted recovery code without leaking how much of it matched.
     *
     * `hash_equals` rather than `===`. A recovery code is a credential, and a
     * comparison that stops at the first wrong character is a comparison whose
     * duration says where it stopped.
     */
    public function matchesRecoveryCode(#[SensitiveParameter] string $candidate, #[SensitiveParameter] string $stored): bool
    {
        return hash_equals($stored, strtolower(trim($candidate)));
    }
}
